### ISSUE TITLE
Were you able to use swc-project/swc#1465 to work with Linaria?

### ISSUE THREAD

**Issue by jkonowitch** [arendjr/linaria-swc#1]
Curious how that went, and whether you have any resources that might be useful? Thanks in advance 🙏

**Comment by arendjr** [comment]
No, not at all :( This project was an attempt at porting Linaria to SWC, but it got stalled pretty quickly when I realized the scope of it (basically a rewrite of the Linaria project) and learned that SWC wanted to support Babel plugins out of the box. I’m afraid the latter didn’t materialize yet either.

On the plus side, I do think there’s an SWC plugin for styled-components out there nowadays, so it’s probably more feasible to migrate to that instead.

**Comment by jkonowitch** [comment]
Got it. We recently ported an app over to Linaria to minimize runtime cost. But then saw this shiny new compiler and was hoping we could take advantage. Well - will post back here if I end up learning any more about a way forward here. Thanks for the response!

**Comment by arendjr** [comment]
No plans on this anymore, sorry.
